# Generated by Django 6.0.2 on 2026-02-05 10:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('datetime', 'DateTime'), ('boolean', 'Boolean'), ('dropdown', 'Dropdown'), ('multiselect', 'Multi-Select'), ('file', 'File Attachment'), ('url', 'URL')], max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('is_searchable', models.BooleanField(default=True)),
                ('default_value', models.TextField(blank=True)),
                ('validation_rules', models.JSONField(blank=True, default=dict)),
                ('dropdown_options', models.JSONField(blank=True, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('help_text', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'items_custom_field',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ItemCustomFieldValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value_text', models.TextField(blank=True)),
                ('value_number', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('value_datetime', models.DateTimeField(blank=True, null=True)),
                ('value_boolean', models.BooleanField(blank=True, null=True)),
                ('value_json', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'items_custom_field_value',
            },
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'items_item_type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('unit', models.CharField(default='pieces', max_length=50)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('discontinued', 'Discontinued'), ('pending', 'Pending')], default='active', max_length=50)),
                ('reorder_point', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('reorder_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'items_item',
                'ordering': ['name'],
            },
        ),
    ]
