# Generated by Django 6.0.2 on 2026-02-05 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        ('locations', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.location'),
        ),
        migrations.AddField(
            model_name='item',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='itemcustomfieldvalue',
            name='custom_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.customfield'),
        ),
        migrations.AddField(
            model_name='itemcustomfieldvalue',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_values', to='items.item'),
        ),
        migrations.AddField(
            model_name='itemtype',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='items.itemtype'),
        ),
        migrations.AddField(
            model_name='itemtype',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='items.itemtype'),
        ),
        migrations.AddField(
            model_name='customfield',
            name='item_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='items.itemtype'),
        ),
        migrations.AlterUniqueTogether(
            name='itemcustomfieldvalue',
            unique_together={('item', 'custom_field')},
        ),
        migrations.AlterUniqueTogether(
            name='itemtype',
            unique_together={('tenant', 'name')},
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['tenant', 'item_type'], name='items_item_tenant__f51d72_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['tenant', 'status'], name='items_item_tenant__665ada_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['tenant', 'location'], name='items_item_tenant__7d096f_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['tenant', 'code'], name='items_item_tenant__6d2071_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('tenant', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='customfield',
            unique_together={('item_type', 'name')},
        ),
    ]
