# Generated by Django 6.0.2 on 2026-02-05 09:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('industry', models.CharField(choices=[('hospital', 'Hospital'), ('factory', 'Factory'), ('clinic', 'Clinic'), ('library', 'Library'), ('school', 'School'), ('retail', 'Retail'), ('restaurant', 'Restaurant'), ('construction', 'Construction'), ('warehouse', 'Warehouse'), ('other', 'Other')], default='other', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('subscription_tier', models.CharField(choices=[('starter', 'Starter'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], default='starter', max_length=50)),
            ],
            options={
                'db_table': 'tenants_tenant',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TenantConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('date_format', models.CharField(default='YYYY-MM-DD', max_length=20)),
                ('time_format', models.CharField(default='HH:mm:ss', max_length=20)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('language', models.CharField(default='en', max_length=10)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tenant_logos/')),
                ('primary_color', models.CharField(default='#0066FF', max_length=7)),
                ('secondary_color', models.CharField(default='#1A1A2E', max_length=7)),
                ('enable_workflows', models.BooleanField(default=True)),
                ('enable_notifications', models.BooleanField(default=True)),
                ('enable_reports', models.BooleanField(default=True)),
                ('enable_api', models.BooleanField(default=True)),
                ('enable_barcode', models.BooleanField(default=False)),
                ('enable_batch_tracking', models.BooleanField(default=False)),
                ('enable_serial_tracking', models.BooleanField(default=False)),
                ('max_users', models.IntegerField(default=10)),
                ('max_items', models.IntegerField(default=1000)),
                ('max_locations', models.IntegerField(default=50)),
                ('max_storage_mb', models.IntegerField(default=1000)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuration', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenants_configuration',
            },
        ),
    ]
