# Generated by Django 5.2.6 on 2026-02-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantconfiguration',
            name='enabled_modules',
            field=models.JSONField(blank=True, default=list, help_text="List of enabled module identifiers, e.g. ['items', 'transactions', 'workflows']"),
        ),
        migrations.AddField(
            model_name='tenantconfiguration',
            name='max_bulk_operation_size',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='tenantconfiguration',
            name='max_file_upload_mb',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='tenantconfiguration',
            name='max_import_rows',
            field=models.IntegerField(default=100000),
        ),
        migrations.AddField(
            model_name='tenantconfiguration',
            name='max_item_type_depth',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='tenantconfiguration',
            name='max_location_depth',
            field=models.IntegerField(default=15),
        ),
    ]
