# Generated by Django 6.0.2 on 2026-02-05 10:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('location_type', models.CharField(choices=[('warehouse', 'Warehouse'), ('building', 'Building'), ('floor', 'Floor'), ('room', 'Room'), ('aisle', 'Aisle'), ('shelf', 'Shelf'), ('bin', 'Bin'), ('zone', 'Zone'), ('other', 'Other')], default='other', max_length=50)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('capacity', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('capacity_unit', models.CharField(default='items', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='locations.location')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'locations_location',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['tenant', 'parent'], name='locations_l_tenant__886a87_idx'), models.Index(fields=['tenant', 'is_active'], name='locations_l_tenant__61c466_idx'), models.Index(fields=['tenant', 'location_type'], name='locations_l_tenant__4592dc_idx')],
                'unique_together': {('tenant', 'code')},
            },
        ),
    ]
